### ISSUE TITLE
After spawn

### ISSUE THREAD

**Issue by Wjaas** [Thunderstorm441/ts_spawnselect#2]
Hey! I got a question. How can I make the menu visible again after people have spawned. Like if someone wants to go somewhere else they can just press F5 and the menu opens again. Where and how do I put this code?

Can I do like this?

`Citizen.CreateThread(function()
if isControlJustPressed(1, 51) then
TriggerEvent(“ts_spawnselect:openMenu”)
end
end)
`

**Comment by Thunderstorm441** [comment]
yes, that will work if you change it slightly, you can put it anywhere clientside.
```
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1)
        if isControlJustPressed(1, 51) then 
            TriggerEvent(“ts_spawnselect:openMenu”) 
        end
    end 
end)
```
